// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmjs7y3OVzHV0hWFpcGATejjEt7gUEjtI',
    appId: '1:592303375849:web:154fe9f0116d30e6d9b778',
    messagingSenderId: '592303375849',
    projectId: 'todo-bloc-1cc94',
    authDomain: 'todo-bloc-1cc94.firebaseapp.com',
    storageBucket: 'todo-bloc-1cc94.firebasestorage.app',
    measurementId: 'G-DM83FBSZEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7gF1wnn5DVV2f0PFq_pD65NGeOwXlRGU',
    appId: '1:592303375849:android:ec86e272ec006e62d9b778',
    messagingSenderId: '592303375849',
    projectId: 'todo-bloc-1cc94',
    storageBucket: 'todo-bloc-1cc94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLNoVOIt5LVHkLZVXJLV7SYJMssz6_UA',
    appId: '1:592303375849:ios:ba96d2ee53271153d9b778',
    messagingSenderId: '592303375849',
    projectId: 'todo-bloc-1cc94',
    storageBucket: 'todo-bloc-1cc94.firebasestorage.app',
    iosBundleId: 'com.example.todoBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLNoVOIt5LVHkLZVXJLV7SYJMssz6_UA',
    appId: '1:592303375849:ios:ba96d2ee53271153d9b778',
    messagingSenderId: '592303375849',
    projectId: 'todo-bloc-1cc94',
    storageBucket: 'todo-bloc-1cc94.firebasestorage.app',
    iosBundleId: 'com.example.todoBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmjs7y3OVzHV0hWFpcGATejjEt7gUEjtI',
    appId: '1:592303375849:web:cb4e854235ba2b27d9b778',
    messagingSenderId: '592303375849',
    projectId: 'todo-bloc-1cc94',
    authDomain: 'todo-bloc-1cc94.firebaseapp.com',
    storageBucket: 'todo-bloc-1cc94.firebasestorage.app',
    measurementId: 'G-N1FCMQ9C5X',
  );
}
